# generated by Neptune Namespaces v2.x.x
# file: tests/Caffeine/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Caffeine ||
Tests.addNamespace 'Caffeine', class Caffeine extends Neptune.Base
  ;
require './JsGen/namespace'