# generated by Neptune Namespaces v2.x.x
# file: tests/Caffeine/JsGen/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  OutputGenerator: require './OutputGenerator'
require './NodeTypes'