# generated by Neptune Namespaces v2.x.x
# file: tests/Caffeine/JsGen/namespace.coffee

Caffeine = require '../namespace'
module.exports = Caffeine.JsGen ||
Caffeine.addNamespace 'JsGen', class JsGen extends Neptune.Base
  ;
require './NodeTypes/namespace'