# generated by Neptune Namespaces v2.x.x
# file: Caffeine/JsGen/NodeTypes/namespace.coffee

JsGen = require '../namespace'
module.exports = JsGen.NodeTypes ||
JsGen.addNamespace 'NodeTypes', class NodeTypes extends Neptune.Base
  ;
