# generated by Neptune Namespaces v2.x.x
# file: Caffeine/JsGen/OutputGenerator/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  JsgOut:           require './JsgOut'          
  JsgOutBase:       require './JsgOutBase'      
  JsgOutLines:      require './JsgOutLines'     
  JsgOutSpaced:     require './JsgOutSpaced'    
  JsgOutStatements: require './JsgOutStatements'