# generated by Neptune Namespaces v2.x.x
# file: Caffeine/JsGen/OutputGenerator/namespace.coffee

JsGen = require '../namespace'
module.exports = JsGen.OutputGenerator ||
JsGen.addNamespace 'OutputGenerator', class OutputGenerator extends Neptune.Base
  ;
